base: '/shared/youngkim/hw2p2'
submissions: '/shared/youngkim/hw2p2/submissions/'
weights: '/shared/youngkim/hw2p2/weights/'
pretrained: '/shared/youngkim/hw2p2/weights/resnet50-4662-softtriple-sgd0.01-ls0.1-15:19:40:04.pth'