save_name: 'baseline'
device: 'cuda:0'
DATA_DIR: '/kaggle/input/dlhw2p2'
save_path_sub: '/kaggle/working/submission/'
save_path_out: '/kaggle/working/weights/'

resume: False
load_path: '/root/class/cmu/DL/hw1p2/weights/exp20_sam.pth'

DEBUG: False

# learning
epoch: 25
es_patience: 3 # if es_patient == 0, do not early stop.
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR # ReduceLROnPlateau, CosineAnnealingLR
mixed_precision: False

# data
batch_size: 256

# model
batchnorm: True
weight_init: None # kaiming_normal, xavier_uniform, xavier_normal, None

# optimizer
optimizer: sgd # adamw, sgd, sam
lr: 0.1
weight_decay: 0.0001
lr_factor: 0.1
lr_patience: 1
momentum: 0.9

# regularization
rdrop: 0