# @package _global_

defaults:
  - _self_
  - path: custom.yaml

save_name: 'convnext-4772'
dt_string: None
device: 'cuda:0'

DEBUG: False

# learning
resume: False
epoch: 80
es_patience: 0 # if es_patient == 0, do not early stop.
mixed_precision: True

# loss
metric: SoftTripleLoss # SoftTripleLoss, TripletMarginLoss
criterion: CrossEntropyLoss
label_smoothing: 0.1

# data
batch_size: 256

# model
model: my_convnext # vgg19, mobilenet, resnet, resnet50, eff_b4, convnext_t, my_convnext
batchnorm: True
block_nums: [4,7,7,2]

# optimizer
optimizer: sgd # adamw, sgd
scheduler: CosineAnnealingLR # ReduceLROnPlateau, CosineAnnealingLR, StepLR, None
lr: 0.01
weight_decay: 0.01
lr_factor: 0.1 # for ReduceLROnPlateau
lr_patience: 1 # for ReduceLROnPlateau
step_size: 50 # for StepLR
momentum: 0.9

# regularization
dropout: 0
# rdrop: 0