# @package _global_

defaults:
  - _self_
  - path: server.yaml

save_name: 'vgg16'
device: 'cuda:0'

DEBUG: False

# learning
resume: False
epoch: 25
es_patience: 3 # if es_patient == 0, do not early stop.
criterion: CrossEntropyLoss
scheduler: CosineAnnealingLR # ReduceLROnPlateau, CosineAnnealingLR
mixed_precision: True

# data
batch_size: 128

# model
batchnorm: True

# optimizer
optimizer: adamw # adamw, sgd, sam
lr: 0.01
weight_decay: 0.001
lr_factor: 0.1
lr_patience: 1
momentum: 0.9

# regularization
rdrop: 0